services:
  db:
    image: mysql:8.0
    container_name: saas_dev_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapi
    ports:
      - "3306:3306"
    volumes:
      - saas_db_data:/var/lib/mysql

volumes:
  saas_db_data:
