// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApi.Modules.Auth.Persistence;

#nullable disable

namespace MyApi.Modules.Auth.Persistence.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260407094251_InitialAuthModuleMySql")]
    partial class InitialAuthModuleMySql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyApi.Modules.Auth.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AuthPermissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ccf425d8-c99e-4d54-b5f0-1949920727f0"),
                            Description = "Read the authenticated user profile.",
                            Name = "auth.profile.read"
                        },
                        new
                        {
                            Id = new Guid("11a7d0ca-a7aa-49d2-81c2-eb09fbf67e95"),
                            Description = "Update the authenticated user profile.",
                            Name = "auth.profile.update"
                        },
                        new
                        {
                            Id = new Guid("b1daf2a5-3508-4b35-a449-38590f266f59"),
                            Description = "Refresh access tokens.",
                            Name = "auth.tokens.refresh"
                        },
                        new
                        {
                            Id = new Guid("9007725f-8a40-4a4c-9cdb-01e983f7f98d"),
                            Description = "Manage users, roles, and permissions.",
                            Name = "auth.users.manage"
                        });
                });

            modelBuilder.Entity("MyApi.Modules.Auth.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("AuthRefreshTokens", (string)null);
                });

            modelBuilder.Entity("MyApi.Modules.Auth.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AuthRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c6b3d90-5513-4c67-9d7f-5bc2b4e2d9c1"),
                            Description = "Default application user role.",
                            Name = "User"
                        },
                        new
                        {
                            Id = new Guid("0e2714f8-a22d-4ec3-a730-0710bf3efc4c"),
                            Description = "Administrator role with access to auth management operations.",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("MyApi.Modules.Auth.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("AuthRolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("21a9dc48-7e7b-4af5-89b8-c792d2113348"),
                            PermissionId = new Guid("ccf425d8-c99e-4d54-b5f0-1949920727f0"),
                            RoleId = new Guid("0c6b3d90-5513-4c67-9d7f-5bc2b4e2d9c1")
                        },
                        new
                        {
                            Id = new Guid("6851ee5d-703e-41ef-aaad-071761761ce2"),
                            PermissionId = new Guid("11a7d0ca-a7aa-49d2-81c2-eb09fbf67e95"),
                            RoleId = new Guid("0c6b3d90-5513-4c67-9d7f-5bc2b4e2d9c1")
                        },
                        new
                        {
                            Id = new Guid("f477c9b1-ac9a-4a1d-ab88-bd9302c970f1"),
                            PermissionId = new Guid("b1daf2a5-3508-4b35-a449-38590f266f59"),
                            RoleId = new Guid("0c6b3d90-5513-4c67-9d7f-5bc2b4e2d9c1")
                        },
                        new
                        {
                            Id = new Guid("5ba40513-f48e-4671-9327-23344dacac51"),
                            PermissionId = new Guid("ccf425d8-c99e-4d54-b5f0-1949920727f0"),
                            RoleId = new Guid("0e2714f8-a22d-4ec3-a730-0710bf3efc4c")
                        },
                        new
                        {
                            Id = new Guid("f6560fd2-81b7-4673-ad0d-fc82ef3222db"),
                            PermissionId = new Guid("11a7d0ca-a7aa-49d2-81c2-eb09fbf67e95"),
                            RoleId = new Guid("0e2714f8-a22d-4ec3-a730-0710bf3efc4c")
                        },
                        new
                        {
                            Id = new Guid("9d23d6d5-b013-41a4-b9bb-430f8dd2e74d"),
                            PermissionId = new Guid("b1daf2a5-3508-4b35-a449-38590f266f59"),
                            RoleId = new Guid("0e2714f8-a22d-4ec3-a730-0710bf3efc4c")
                        },
                        new
                        {
                            Id = new Guid("77832da3-a93e-4d8b-b18b-31de7476c959"),
                            PermissionId = new Guid("9007725f-8a40-4a4c-9cdb-01e983f7f98d"),
                            RoleId = new Guid("0e2714f8-a22d-4ec3-a730-0710bf3efc4c")
                        });
                });

            modelBuilder.Entity("MyApi.Modules.Auth.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AuthUsers", (string)null);
                });

            modelBuilder.Entity("MyApi.Modules.Auth.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("AuthUserRoles", (string)null);
                });

            modelBuilder.Entity("MyApi.Modules.Auth.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MyApi.Modules.Auth.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Modules.Auth.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("MyApi.Modules.Auth.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Modules.Auth.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MyApi.Modules.Auth.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("MyApi.Modules.Auth.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Modules.Auth.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Modules.Auth.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("MyApi.Modules.Auth.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MyApi.Modules.Auth.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
